namespace: workshop-content

image: quay.io/matrix-workshop/harden-the-box:latest
replicas: 1
port: 8080

build:
  enabled: true
  gitUri: https://github.com/gsampaio-rh/matrix-harden-the-box.git
  gitRef: main
  dockerfilePath: build/Dockerfile

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

env:
  teamPrefix: team
  defaultTeamCount: "10"
  adminKey: ""

persistence:
  enabled: true
  size: 100Mi
  # storageClass: ""
