apiVersion: v1
kind: Service
metadata:
  name: harden-the-box
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "htb.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "htb.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      name: http
