{{- if .Values.build.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: harden-the-box
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "htb.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- end }}
